class FunctionTimeoutException(Exception):
    pass
  
class TestException(Exception):
    pass